"""fix user, shooting, theme and group

Revision ID: 0ee5c29adb25
Revises: 7909ea6c4420
Create Date: 2024-03-14 23:06:59.756995

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ee5c29adb25'
down_revision: Union[str, None] = '7909ea6c4420'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('groupshooting',
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('shhoting_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['group.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['shhoting_id'], ['shooting.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('group_id', 'shhoting_id')
    )
    op.create_table('groupuser',
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['group.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('group_id', 'user_id')
    )
    op.alter_column('shooting', 'theme_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('shooting', 'group_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint('shooting_theme_id_fkey', 'shooting', type_='foreignkey')
    op.drop_constraint('shooting_group_id_fkey', 'shooting', type_='foreignkey')
    op.create_foreign_key(None, 'shooting', 'group', ['group_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'shooting', 'theme', ['theme_id'], ['id'], ondelete='CASCADE')
    op.alter_column('user', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('user', 'phone',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('user', 'group_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint('user_group_id_fkey', 'user', type_='foreignkey')
    op.create_foreign_key(None, 'user', 'group', ['group_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.create_foreign_key('user_group_id_fkey', 'user', 'group', ['group_id'], ['id'])
    op.alter_column('user', 'group_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('user', 'phone',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('user', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint(None, 'shooting', type_='foreignkey')
    op.drop_constraint(None, 'shooting', type_='foreignkey')
    op.create_foreign_key('shooting_group_id_fkey', 'shooting', 'group', ['group_id'], ['id'])
    op.create_foreign_key('shooting_theme_id_fkey', 'shooting', 'theme', ['theme_id'], ['id'])
    op.alter_column('shooting', 'group_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('shooting', 'theme_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_table('groupuser')
    op.drop_table('groupshooting')
    # ### end Alembic commands ###
