"""fix kindergarten and town

Revision ID: 4521362b0d93
Revises: e0675197763f
Create Date: 2024-03-14 21:48:53.883728

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4521362b0d93'
down_revision: Union[str, None] = 'e0675197763f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('news',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('town',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('kindergarten', sa.Column('town_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'kindergarten', 'town', ['town_id'], ['id'], ondelete='CASCADE')
    op.drop_column('kindergarten', 'town')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('kindergarten', sa.Column('town', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'kindergarten', type_='foreignkey')
    op.drop_column('kindergarten', 'town_id')
    op.drop_table('town')
    op.drop_table('payment')
    op.drop_table('news')
    # ### end Alembic commands ###
