"""fix basket and user

Revision ID: ea1cb7f85fa8
Revises: a8167e9195a9
Create Date: 2024-03-14 23:29:24.064603

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea1cb7f85fa8'
down_revision: Union[str, None] = 'a8167e9195a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('basket', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint('basket_user_id_fkey', 'basket', type_='foreignkey')
    op.create_foreign_key(None, 'basket', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'basket', type_='foreignkey')
    op.create_foreign_key('basket_user_id_fkey', 'basket', 'user', ['user_id'], ['id'])
    op.alter_column('basket', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
